services:
  - type: web
    name: open-ro-dashboard
    env: python
    plan: free
    pythonVersion: 3.12
    startCommand: gunicorn -w 1 -k uvicorn.workers.UvicornWorker main:app
    buildCommand: pip install -r requirements.txt
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHONUNBUFFERED
        value: true
